import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import { ModalProvider } from "@/providers/ModalProvider";
import { ToggleProvider } from "@/providers/ToggleProvider";
import LoginModal from "@/components/ui/Modal/LoginModal";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const onest = Onest({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"]
});


export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${onest.className} bg-primary`}>
        <ModalProvider>
          <ToggleProvider>

            {/* Login */}
            <LoginModal />

            <div className="flex h-screen flex-col ">
              <Navbar />
              <main className="flex-1">
                {children}
              </main>
              <Footer />
            </div>
          </ToggleProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
